# wrangler.toml (at the root of your project)
name = "my-fileshare-pages-app" # Name of your Cloudflare Pages project
pages_build_output_dir = "./frontend/dist" # The output directory of your frontend build
functions_directory = "./functions" # The directory containing your Pages Functions

compatibility_date = "2025-06-05" # Use the current date or later

[[r2_buckets]]
binding = 'FILES_BUCKET' # This will be accessible as env.FILES_BUCKET in your Pages Functions
bucket_name = 'your-r2-bucket-name' # IMPORTANT: Replace with your actual R2 bucket name

[[d1_databases]]
binding = 'DB' # This will be accessible as env.DB in your Pages Functions
database_name = 'your-d1-database-name' # IMPORTANT: Replace with your actual D1 database name
database_id = 'your-d1-database-id' # IMPORTANT: Replace with your actual D1 database ID
