# wrangler.toml (at the root of your project)
name = "fileshare-project" # Name of your Cloudflare Pages project
pages_build_output_dir = "./frontend/dist" # The output directory of your frontend build
functions_directory = "./functions" # The directory containing your Pages Functions
compatibility_date = "2025-06-05" # Use the current date or later

[[r2_buckets]]
binding = 'FILES_BUCKET' # This will be accessible as env.FILES_BUCKET in your Pages Functions
bucket_name = 'filesharing' # IMPORTANT: Replace with your actual R2 bucket name

[[d1_databases]]
binding = 'DB' # This will be accessible as env.DB in your Pages Functions
database_name = 'filesharing' # IMPORTANT: Replace with your actual D1 database name
database_id = 'ff893b0c-e959-43ca-9604-834691f746f3' # IMPORTANT: Replace with your actual D1 database ID
